### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by andrewgross** [Yipit/pyeqs#7]
Main issue is that we will need abandon `sure`.  Hopefully not `httpretty`.  The `pre-commit` hook makes it seem like it should be pretty straightforward to transfer the code itself, once the libs work.

**Comment by mtford90** [comment]
+1

**Comment by andrewgross** [comment]
Will take another swing at this.

**Comment by mtford90** [comment]
Awesome, from what I can tell looking at the `sure` repo they have python 3 support now? At least they have `six` in their requirements.txt anyhow: https://github.com/gabrielfalcao/sure/blob/master/requirements.txt so they're at least attempting it ^^

**Comment by andrewgross** [comment]
Yeah it should work with it, I believe they added it a while back.

**Comment by andrewgross** [comment]
Added in `0.7.0`

**Comment by mtford90** [comment]
Fantastic, cheers - I look forward to playing with it!
